---
version: "3"
services:
  ## Postgres database
  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres_data_engineering_project
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example_password
      - POSTGRES_DB=data_engineering_project
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  ## MySQL database
  mysql-db:
    image: mysql:8.0
    container_name: mysql_data_engineering_project
    restart: unless-stopped
    environment:
      # root password
      - MYSQL_ROOT_PASSWORD=example_password
      - MYSQL_DATABASE=data_engineering_project
      # user password
      - MYSQL_USER=your_mysql_user
      - MYSQL_PASSWORD=your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql

#  ## Microsoft SQL Server database
#  # username: sa
#  mssql-db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: mssql_data_engineering_project
#    restart: unless-stopped
#    environment:
#      - SA_PASSWORD=example_password
#      - ACCEPT_EULA=Y
#      - MSSQL_PID=Express
#      - MSSQL_DATABASE=data_engineering_project
#      - SA_USERNAME=your_mssql_user
#    ports:
#      - "1433:1433"
#    volumes:
#      - ./db/mssql:/var/opt/mssql

  ## Airflow
  apache-airflow:
    image: apache-airflow:latest
    restart: unless-stopped
    # TODO if not kaggle.json change this variables with your values
#    environment:
#      - KAGGLE_USERNAME=kaggle_username
#      - KAGGLE_KEY=kaggle_key
    volumes:
      - ./airflow:/opt/airflow
      - ~/.kaggle:/home/airflow/.kaggle
    ports:
      - "8080:8080"
    command: airflow standalone
